### ISSUE TITLE
NIP-28 public chats

### ISSUE THREAD

**Issue by brenzi** [ethicnology/dart-nostr#17]
It would be great to have this supported for https://github.com/encointer/encointer-wallet-flutter/issues/993
Any plans to implement it soon? We may be able to contribute, but not immediately

**Comment by ethicnology** [comment]
Hey, after reading the `nip28` i don't really see what are your support expectations since it already works with the current Event class filled with the correct `kind`, `content` and `tags`…

Maybe you want helpers to encode/decode tags or a class for the channel meta-data, if so, please contribute taking as template my recent work on [nip2](https://github.com/ethicnology/dart-nostr/blob/develop/lib/src/nips/nip_002.dart)…

The next priority on board will probably be https://github.com/ethicnology/dart-nostr/issues/15
